export interface Lesson {
  id: number;
  title: string;
  duration: string;
  free: boolean;
  completed: boolean;
}

export interface Question {
  id: number;
  question: string;
  options: string[];
  correct: number;
}

export interface CourseData {
  category: string;
  id: number;
  title: string;
  description: string;
  rating: number;
  students: number;
  duration: string;
  lessonsCount: number;
  price: number;
  instructor: string;
  topics: string[];
  lessons: Lesson[];
  questions: Question[];
  certificateTitle: string;
  emoji: string;
  color: string;
  gradientFrom: string;
  gradientTo: string;
}

export const coursesData: Record<number, CourseData> = {
  1: {
    id: 1,
    category: "Front-End",
    title: "React.js - تطوير واجهات المستخدم",
    description: "تعلم React.js من الصفر حتى الاحتراف مع بناء مشاريع حقيقية. الكورس يغطي Hooks, Context API, Redux, Next.js وأكتر.",
    rating: 4.8,
    students: 1200,
    duration: "25 ساعة",
    lessonsCount: 40,
    price: 49,
    instructor: "Ahmed Salah",
    topics: ["مقدمة في React", "Components & JSX", "Hooks", "State Management", "Routing", "Projects"],
    lessons: [
      { id: 1, title: "ما هو React؟", duration: "10:45", free: true, completed: true },
      { id: 2, title: "إعداد البيئة", duration: "15:20", free: true, completed: true },
      { id: 3, title: "JSX والمكونات", duration: "20:15", free: false, completed: false },
      { id: 4, title: "Props & State", duration: "25:00", free: false, completed: false },
      { id: 5, title: "Hooks", duration: "30:10", free: false, completed: false },
      { id: 6, title: "المشاريع العملية", duration: "45:00", free: false, completed: false },
    ],
    questions: [
      { id: 1, question: "ما هي المكتبة التي تستخدم لبناء واجهات المستخدم في JavaScript؟", options: ["Angular", "React", "Vue", "Django"], correct: 1 },
      { id: 2, question: "ما هو Hook المستخدم لإدارة الحالة (State) في React؟", options: ["useEffect", "useContext", "useState", "useReducer"], correct: 2 },
      { id: 3, question: "ما هي لغة البرمجة التي تستخدم بشكل أساسي في تطوير الذكاء الاصطناعي؟", options: ["Java", "C++", "Python", "Ruby"], correct: 2 },
      { id: 4, question: "ما هو الـ Framework المستخدم لتطوير تطبيقات الموبايل متعددة المنصات؟", options: ["React Native", "Flutter", "Ionic", "جميع ما سبق"], correct: 3 },
      { id: 5, question: "ما هي لغة الاستعلام المستخدمة للتعامل مع قواعد البيانات العلائقية؟", options: ["NoSQL", "GraphQL", "SQL", "MongoDB"], correct: 2 },
    ],
    certificateTitle: "React.js - تطوير واجهات المستخدم",
    emoji: "⚛️",
    color: "from-blue-500 to-cyan-400",
    gradientFrom: "from-blue-600/20",
    gradientTo: "to-purple-600/20",
  },
  2: {
    id: 2,
    category: "Back-End",
    title: "Python - البرمجة بلغة بايثون",
    description: "تعلم Python من الصفر حتى الاحتراف. الكورس يغطي الأساسيات، OOP، Data Analysis، Web Scraping، Django وأكتر.",
    rating: 4.9,
    students: 980,
    duration: "30 ساعة",
    lessonsCount: 35,
    price: 39,
    instructor: "Mohamed Ali",
    topics: ["أساسيات Python", "Data Types", "OOP", "File Handling", "Web Scraping", "Django Basics"],
    lessons: [
      { id: 1, title: "مقدمة في Python", duration: "12:00", free: true, completed: true },
      { id: 2, title: "Variables و Data Types", duration: "18:30", free: true, completed: true },
      { id: 3, title: "Control Flow", duration: "22:15", free: false, completed: false },
      { id: 4, title: "Functions", duration: "25:00", free: false, completed: false },
      { id: 5, title: "OOP في Python", duration: "35:10", free: false, completed: false },
      { id: 6, title: "Django Basics", duration: "40:00", free: false, completed: false },
    ],
    questions: [
      { id: 1, question: "ما هو النوع الذي يستخدم لتخزين مجموعة غير قابلة للتعديل في Python؟", options: ["List", "Dictionary", "Tuple", "Set"], correct: 2 },
      { id: 2, question: "ما هي الدالة المستخدمة لطباعة النص في Python؟", options: ["echo", "print", "console.log", "printf"], correct: 1 },
      { id: 3, question: "ما هو الـ Framework الشهير لتطوير الويب بـ Python؟", options: ["Flask", "Django", "FastAPI", "جميع ما سبق"], correct: 3 },
      { id: 4, question: "ما هي المكتبة المستخدمة لتحليل البيانات في Python؟", options: ["NumPy", "Pandas", "Matplotlib", "جميع ما سبق"], correct: 3 },
      { id: 5, question: "ما هو الـ decorator في Python؟", options: ["دالة", "كلاس", "دالة تعدل دالة أخرى", "متغير"], correct: 2 },
    ],
    certificateTitle: "Python - البرمجة بلغة بايثون",
    emoji: "🐍",
    color: "from-yellow-500 to-green-400",
    gradientFrom: "from-yellow-600/20",
    gradientTo: "to-green-600/20",
  },
  3: {
    id: 3,
    category: "Full Stack",
    title: "Full Stack - تطوير المواقع الكاملة",
    description: "تعلم تطوير المواقع الكاملة من Front-End لـ Back-End. الكورس يغطي React, Node.js, MongoDB, Docker وأكتر.",
    rating: 4.9,
    students: 750,
    duration: "45 ساعة",
    lessonsCount: 50,
    price: 59,
    instructor: "Sara Ahmed",
    topics: ["HTML/CSS", "JavaScript", "React", "Node.js", "MongoDB", "Deployment"],
    lessons: [
      { id: 1, title: "مقدمة في Full Stack", duration: "15:00", free: true, completed: true },
      { id: 2, title: "HTML & CSS Advanced", duration: "20:30", free: true, completed: true },
      { id: 3, title: "JavaScript ES6+", duration: "25:15", free: false, completed: false },
      { id: 4, title: "React & State Management", duration: "30:00", free: false, completed: false },
      { id: 5, title: "Node.js & Express", duration: "35:10", free: false, completed: false },
      { id: 6, title: "Deployment & CI/CD", duration: "40:00", free: false, completed: false },
    ],
    questions: [
      { id: 1, question: "ما هو الـ Stack المستخدم في MERN؟", options: ["MySQL", "MongoDB", "PostgreSQL", "SQLite"], correct: 1 },
      { id: 2, question: "ما هي الـ HTTP Method المستخدمة لتحديث بيانات جزئية؟", options: ["PUT", "PATCH", "POST", "GET"], correct: 1 },
      { id: 3, question: "ما هو الـ Tool المستخدم لحاويات التطبيقات؟", options: ["Git", "Docker", "Jenkins", "Nginx"], correct: 1 },
      { id: 4, question: "ما هي الـ Database NoSQL الأشهر؟", options: ["MySQL", "MongoDB", "Oracle", "SQL Server"], correct: 1 },
      { id: 5, question: "ما هو الـ Protocol المستخدم لنقل البيانات بشكل آمن؟", options: ["HTTP", "FTP", "HTTPS", "SMTP"], correct: 2 },
    ],
    certificateTitle: "Full Stack - تطوير المواقع الكاملة",
    emoji: "🚀",
    color: "from-purple-500 to-pink-400",
    gradientFrom: "from-purple-600/20",
    gradientTo: "to-pink-600/20",
  },
  4: {
    id: 4,
    category: "Back-End",
    title: "Node.js - تطوير الخوادم",
    description: "تعلم Node.js وExpress.js لبناء خوادم قوية و scalable APIs. الكورس يغطي REST APIs, Authentication, WebSockets وأكتر.",
    rating: 4.7,
    students: 890,
    duration: "28 ساعة",
    lessonsCount: 32,
    price: 49,
    instructor: "Khaled Mahmoud",
    topics: ["Node.js Basics", "Express.js", "REST APIs", "Authentication", "Database Integration", "Real-time"],
    lessons: [
      { id: 1, title: "مقدمة في Node.js", duration: "12:00", free: true, completed: true },
      { id: 2, title: "Modules و NPM", duration: "18:30", free: true, completed: true },
      { id: 3, title: "Express.js Basics", duration: "22:15", free: false, completed: false },
      { id: 4, title: "REST APIs", duration: "28:00", free: false, completed: false },
      { id: 5, title: "Authentication JWT", duration: "32:10", free: false, completed: false },
      { id: 6, title: "WebSockets", duration: "35:00", free: false, completed: false },
    ],
    questions: [
      { id: 1, question: "ما هو الـ Module System في Node.js؟", options: ["AMD", "CommonJS", "ES6 Modules", "جميع ما سبق"], correct: 3 },
      { id: 2, question: "ما هي الـ Middleware في Express؟", options: ["دالة", "كلاس", "متغير", "ملف"], correct: 0 },
      { id: 3, question: "ما هو الـ Tool لإدارة حزم Node.js؟", options: ["pip", "npm", "composer", "gem"], correct: 1 },
      { id: 4, question: "ما هي الـ Method لجلب البيانات في HTTP؟", options: ["POST", "GET", "DELETE", "PUT"], correct: 1 },
      { id: 5, question: "ما هو الـ Token المستخدم للمصادقة؟", options: ["OAuth", "JWT", "API Key", "جميع ما سبق"], correct: 3 },
    ],
    certificateTitle: "Node.js - تطوير الخوادم",
    emoji: "🟢",
    color: "from-green-500 to-emerald-400",
    gradientFrom: "from-green-600/20",
    gradientTo: "to-emerald-600/20",
  },
  5: {
    id: 5,
    category: "Mobile",
    title: "Flutter - تطوير تطبيقات الموبايل",
    description: "تعلم Flutter وDart لبناء تطبيقات موبايل iOS و Android بكود واحد. الكورس يغطي Widgets, State Management, Firebase وأكتر.",
    rating: 4.8,
    students: 650,
    duration: "32 ساعة",
    lessonsCount: 38,
    price: 49,
    instructor: "Nora Samy",
    topics: ["Dart Basics", "Widgets", "State Management", "Navigation", "Firebase", "Deployment"],
    lessons: [
      { id: 1, title: "مقدمة في Flutter", duration: "10:00", free: true, completed: true },
      { id: 2, title: "Dart Basics", duration: "20:30", free: true, completed: true },
      { id: 3, title: "Widgets", duration: "25:15", free: false, completed: false },
      { id: 4, title: "State Management", duration: "30:00", free: false, completed: false },
      { id: 5, title: "Firebase Integration", duration: "28:10", free: false, completed: false },
      { id: 6, title: "Deployment", duration: "35:00", free: false, completed: false },
    ],
    questions: [
      { id: 1, question: "ما هي اللغة المستخدمة في Flutter؟", options: ["Java", "Kotlin", "Dart", "Swift"], correct: 2 },
      { id: 2, question: "ما هو الـ Widget الأساسي في Flutter؟", options: ["Container", "Scaffold", "MaterialApp", "جميع ما سبق"], correct: 3 },
      { id: 3, question: "ما هي الـ State Management الأشهر في Flutter؟", options: ["Provider", "Bloc", "Riverpod", "جميع ما سبق"], correct: 3 },
      { id: 4, question: "ما هو الـ Platform الذي يدعمه Flutter؟", options: ["iOS", "Android", "Web", "جميع ما سبق"], correct: 3 },
      { id: 5, question: "ما هو الـ Widget المستخدم لإنشاء قائمة؟", options: ["Column", "ListView", "Row", "Stack"], correct: 1 },
    ],
    certificateTitle: "Flutter - تطوير تطبيقات الموبايل",
    emoji: "📱",
    color: "from-cyan-500 to-blue-400",
    gradientFrom: "from-cyan-600/20",
    gradientTo: "to-blue-600/20",
  },
  6: {
    id: 6,
    category: "Database",
    title: "SQL - قواعد البيانات",
    description: "تعلم SQL من الصفر حتى الاحتراف. الكورس يغطي Queries, Joins, Subqueries, Normalization, Indexing وأكتر.",
    rating: 4.6,
    students: 1100,
    duration: "20 ساعة",
    lessonsCount: 25,
    price: 29,
    instructor: "Ahmed Khaled",
    topics: ["SQL Basics", "SELECT Queries", "Joins", "Subqueries", "Normalization", "Indexing"],
    lessons: [
      { id: 1, title: "مقدمة في SQL", duration: "10:00", free: true, completed: true },
      { id: 2, title: "SELECT و WHERE", duration: "15:30", free: true, completed: true },
      { id: 3, title: "Joins", duration: "20:15", free: false, completed: false },
      { id: 4, title: "Subqueries", duration: "22:00", free: false, completed: false },
      { id: 5, title: "Normalization", duration: "18:10", free: false, completed: false },
      { id: 6, title: "Indexing و Optimization", duration: "25:00", free: false, completed: false },
    ],
    questions: [
      { id: 1, question: "ما هو الـ Clause المستخدم لتصفية النتائج؟", options: ["SELECT", "WHERE", "FROM", "ORDER BY"], correct: 1 },
      { id: 2, question: "ما هو الـ Join الذي يعرض السجلات المتطابقة فقط؟", options: ["LEFT JOIN", "RIGHT JOIN", "INNER JOIN", "FULL JOIN"], correct: 2 },
      { id: 3, question: "ما هي الـ Normal Form التي تمنع التكرار؟", options: ["1NF", "2NF", "3NF", "BCNF"], correct: 2 },
      { id: 4, question: "ما هو الـ Index في SQL؟", options: ["جدول", "هيكل لتسريع البحث", "دالة", "Trigger"], correct: 1 },
      { id: 5, question: "ما هو الـ Aggregate Function لحساب المتوسط؟", options: ["SUM", "COUNT", "AVG", "MAX"], correct: 2 },
    ],
    certificateTitle: "SQL - قواعد البيانات",
    emoji: "🗄️",
    color: "from-orange-500 to-red-400",
    gradientFrom: "from-orange-600/20",
    gradientTo: "to-red-600/20",
  },
  7: {
    id: 7,
    category: "UI/UX",
    title: "UI/UX - تصميم واجهات وتجربة المستخدم",
    description: "تعلم أساسيات التصميم، Figma، Design Systems، User Research وأكتر. ابنِ واجهات جميلة وسهلة الاستخدام.",
    rating: 4.7,
    students: 640,
    duration: "22 ساعة",
    lessonsCount: 28,
    price: 39,
    instructor: "Mariam Hassan",
    topics: ["Design Principles", "Figma", "Wireframing", "Prototyping", "Design Systems", "User Research"],
    lessons: [
      { id: 1, title: "مقدمة في UI/UX", duration: "12:00", free: true, completed: false },
      { id: 2, title: "مبادئ التصميم", duration: "18:30", free: true, completed: false },
      { id: 3, title: "Figma Basics", duration: "22:15", free: false, completed: false },
      { id: 4, title: "Wireframing & Prototyping", duration: "28:00", free: false, completed: false },
      { id: 5, title: "Design Systems", duration: "32:10", free: false, completed: false },
      { id: 6, title: "User Research & Testing", duration: "35:00", free: false, completed: false },
    ],
    questions: [
      { id: 1, question: "ما هي الأداة الأشهر لتصميم الواجهات؟", options: ["Photoshop", "Figma", "Illustrator", "Sketch"], correct: 1 },
      { id: 2, question: "ما هو الـ Wireframe؟", options: ["تصميم نهائي", "هيكل أولي للواجهة", "كود", "لوجو"], correct: 1 },
      { id: 3, question: "ما هو الـ Design System؟", options: ["مجموعة قواعد ومكونات موحدة", "برنامج", "خط", "لون"], correct: 0 },
      { id: 4, question: "ما الفرق بين UI و UX؟", options: ["لا فرق", "UI الشكل و UX التجربة", "UI للموبايل فقط", "UX للويب فقط"], correct: 1 },
      { id: 5, question: "ما هو الـ Prototype؟", options: ["نموذج تفاعلي للتصميم", "كود جاهز", "تقرير", "صورة"], correct: 0 },
    ],
    certificateTitle: "UI/UX - تصميم واجهات وتجربة المستخدم",
    emoji: "🎨",
    color: "from-pink-500 to-rose-400",
    gradientFrom: "from-pink-600/20",
    gradientTo: "to-rose-600/20",
  },
  8: {
    id: 8,
    category: "AI Automation",
    title: "AI Automation - أتمتة بالذكاء الاصطناعي",
    description: "تعلم بناء أنظمة أتمتة ذكية بـ AI. الكورس يغطي n8n, Zapier, AI Agents, LLM Integration وأكتر.",
    rating: 4.8,
    students: 420,
    duration: "18 ساعة",
    lessonsCount: 22,
    price: 59,
    instructor: "Omar Farouk",
    topics: ["Automation Basics", "n8n & Make", "AI Agents", "LLM APIs", "Workflows", "Integration"],
    lessons: [
      { id: 1, title: "مقدمة في AI Automation", duration: "12:00", free: true, completed: false },
      { id: 2, title: "أدوات الأتمتة", duration: "18:30", free: true, completed: false },
      { id: 3, title: "بناء Workflows", duration: "25:15", free: false, completed: false },
      { id: 4, title: "AI Agents", duration: "30:00", free: false, completed: false },
      { id: 5, title: "LLM Integration", duration: "28:10", free: false, completed: false },
      { id: 6, title: "مشاريع أتمتة حقيقية", duration: "40:00", free: false, completed: false },
    ],
    questions: [
      { id: 1, question: "ما هو الـ AI Agent؟", options: ["روبوت", "نظام ذكي ينفذ مهام بشكل مستقل", "برنامج بسيط", "فيروس"], correct: 1 },
      { id: 2, question: "ما هي أداة الأتمتة الشهيرة؟", options: ["n8n", "Photoshop", "Excel", "جميع ما سبق"], correct: 0 },
      { id: 3, question: "ما هو LLM؟", options: ["نموذج لغوي كبير", "لغة برمجة", "قاعدة بيانات", "متصفح"], correct: 0 },
      { id: 4, question: "ما هو الـ Workflow؟", options: ["خطوات متسلسلة لمهمة", "ملف", "برنامج", "جهاز"], correct: 0 },
      { id: 5, question: "ما فائدة الأتمتة؟", options: ["توفير الوقت والجهد", "زيادة التكلفة", "تعقيد العمل", "لا شيء"], correct: 0 },
    ],
    certificateTitle: "AI Automation - أتمتة بالذكاء الاصطناعي",
    emoji: "🤖",
    color: "from-violet-500 to-purple-400",
    gradientFrom: "from-violet-600/20",
    gradientTo: "to-purple-600/20",
  },
  9: {
    id: 9,
    category: "Cyber Security",
    title: "Cyber Security - الأمن السيبراني",
    description: "تعلم أساسيات الأمن السيبراني، Ethical Hacking، حماية الشبكات، Penetration Testing وأكتر.",
    rating: 4.8,
    students: 780,
    duration: "35 ساعة",
    lessonsCount: 42,
    price: 69,
    instructor: "Mostafa Adel",
    topics: ["Security Basics", "Network Security", "Ethical Hacking", "Penetration Testing", "Encryption", "Incident Response"],
    lessons: [
      { id: 1, title: "مقدمة في الأمن السيبراني", duration: "15:00", free: true, completed: false },
      { id: 2, title: "أنواع الهجمات", duration: "20:30", free: true, completed: false },
      { id: 3, title: "Network Security", duration: "25:15", free: false, completed: false },
      { id: 4, title: "Ethical Hacking", duration: "32:00", free: false, completed: false },
      { id: 5, title: "Penetration Testing", duration: "38:10", free: false, completed: false },
      { id: 6, title: "Incident Response", duration: "30:00", free: false, completed: false },
    ],
    questions: [
      { id: 1, question: "ما هو الـ Phishing؟", options: ["فيروس", "خداع لسرقة بيانات", "برنامج حماية", "شبكة"], correct: 1 },
      { id: 2, question: "ما هو الـ Firewall؟", options: ["جدار حماية للشبكة", "فيروس", "متصفح", "كابل"], correct: 0 },
      { id: 3, question: "ما هو الـ Penetration Testing؟", options: ["اختراق غير قانوني", "اختبار أمان مُصرّح به", "برمجة", "تصميم"], correct: 1 },
      { id: 4, question: "ما هو التشفير؟", options: ["حذف البيانات", "حماية البيانات بتحويلها", "نسخ البيانات", "ضغطها"], correct: 1 },
      { id: 5, question: "ما هو الـ Ethical Hacking؟", options: ["اختراق ممنوع", "اختبار أمان قانوني بإذن", "سرقة", "برمجة"], correct: 1 },
    ],
    certificateTitle: "Cyber Security - الأمن السيبراني",
    emoji: "🛡️",
    color: "from-red-500 to-orange-400",
    gradientFrom: "from-red-600/20",
    gradientTo: "to-orange-600/20",
  },
  10: {
    id: 10,
    category: "AI/ML",
    title: "AI & Machine Learning - الذكاء الاصطناعي",
    description: "تعلم الذكاء الاصطناعي وتعلم الآلة من الصفر. الكورس يغطي Python, NumPy, Pandas, scikit-learn, Deep Learning وأكتر.",
    rating: 4.9,
    students: 920,
    duration: "40 ساعة",
    lessonsCount: 48,
    price: 79,
    instructor: "Dr. Youssef Nabil",
    topics: ["Python for ML", "NumPy & Pandas", "Supervised Learning", "Neural Networks", "Deep Learning", "Model Deployment"],
    lessons: [
      { id: 1, title: "مقدمة في AI/ML", duration: "15:00", free: true, completed: false },
      { id: 2, title: "Python للـ ML", duration: "22:30", free: true, completed: false },
      { id: 3, title: "NumPy & Pandas", duration: "28:15", free: false, completed: false },
      { id: 4, title: "Supervised Learning", duration: "35:00", free: false, completed: false },
      { id: 5, title: "Neural Networks", duration: "40:10", free: false, completed: false },
      { id: 6, title: "Model Deployment", duration: "35:00", free: false, completed: false },
    ],
    questions: [
      { id: 1, question: "ما هو الـ Supervised Learning؟", options: ["تعلم بدون بيانات", "تعلم ببيانات مُعلّمة", "تعلم بالفيديو", "تعلم ذاتي"], correct: 1 },
      { id: 2, question: "ما هي المكتبة الأشهر للـ ML في Python؟", options: ["Django", "scikit-learn", "Flask", "Requests"], correct: 1 },
      { id: 3, question: "ما هو الـ Neural Network؟", options: ["شبكة كمبيوتر", "نموذج مستوحى من الدماغ", "برنامج", "جهاز"], correct: 1 },
      { id: 4, question: "ما هي مكتبة تحليل البيانات في Python؟", options: ["Pandas", "NumPy", "Matplotlib", "جميع ما سبق"], correct: 3 },
      { id: 5, question: "ما هو الـ Overfitting؟", options: ["نموذج مثالي", "نموذج حفظ البيانات بدل التعلم", "نموذج سريع", "خطأ برمجي"], correct: 1 },
    ],
    certificateTitle: "AI & Machine Learning - الذكاء الاصطناعي",
    emoji: "🧠",
    color: "from-indigo-500 to-blue-400",
    gradientFrom: "from-indigo-600/20",
    gradientTo: "to-blue-600/20",
  },
  11: {
    id: 11,
    category: "Fundamentals",
    title: "Programming Fundamentals - أساسيات البرمجة",
    description: "ابدأ رحلتك في البرمجة من الصفر. الكورس يغطي المنطق البرمجي، Data Structures، Algorithms، Problem Solving وأكتر.",
    rating: 4.9,
    students: 1500,
    duration: "25 ساعة",
    lessonsCount: 30,
    price: 19,
    instructor: "Ahmed Salah",
    topics: ["Logic & Thinking", "Variables & Types", "Control Flow", "Data Structures", "Algorithms", "Problem Solving"],
    lessons: [
      { id: 1, title: "ما هي البرمجة؟", duration: "10:00", free: true, completed: false },
      { id: 2, title: "التفكير المنطقي", duration: "18:30", free: true, completed: false },
      { id: 3, title: "Variables & Data Types", duration: "22:15", free: false, completed: false },
      { id: 4, title: "Data Structures", duration: "30:00", free: false, completed: false },
      { id: 5, title: "Algorithms", duration: "35:10", free: false, completed: false },
      { id: 6, title: "Problem Solving", duration: "40:00", free: false, completed: false },
    ],
    questions: [
      { id: 1, question: "ما هو المتغير (Variable)؟", options: ["رقم", "مكان تخزين بيانات", "دالة", "ملف"], correct: 1 },
      { id: 2, question: "ما هي الـ Loop؟", options: ["تكرار أوامر", "شرط", "متغير", "خطأ"], correct: 0 },
      { id: 3, question: "ما هو الـ Array؟", options: ["متغير واحد", "مجموعة عناصر مرتبة", "دالة", "نص"], correct: 1 },
      { id: 4, question: "ما هي الـ Algorithm؟", options: ["خطوات لحل مشكلة", "لغة برمجة", "برنامج", "جهاز"], correct: 0 },
      { id: 5, question: "ما هو الـ If Statement؟", options: ["تكرار", "شرط", "طباعة", "إدخال"], correct: 1 },
    ],
    certificateTitle: "Programming Fundamentals - أساسيات البرمجة",
    emoji: "💻",
    color: "from-teal-500 to-cyan-400",
    gradientFrom: "from-teal-600/20",
    gradientTo: "to-cyan-600/20",
  },
  12: {
    id: 12,
    category: "Data Analysis",
    title: "Data Analysis - تحليل البيانات",
    description: "تعلم تحليل البيانات من الصفر. الكورس يغطي Excel, SQL, Python, Pandas, Visualization, Power BI وأكتر.",
    rating: 4.7,
    students: 860,
    duration: "30 ساعة",
    lessonsCount: 36,
    price: 49,
    instructor: "Nour El-Din",
    topics: ["Excel Advanced", "SQL for Analysis", "Python & Pandas", "Data Visualization", "Statistics", "Power BI"],
    lessons: [
      { id: 1, title: "مقدمة في تحليل البيانات", duration: "12:00", free: true, completed: false },
      { id: 2, title: "Excel المتقدم", duration: "20:30", free: true, completed: false },
      { id: 3, title: "SQL للتحليل", duration: "25:15", free: false, completed: false },
      { id: 4, title: "Python & Pandas", duration: "32:00", free: false, completed: false },
      { id: 5, title: "Data Visualization", duration: "28:10", free: false, completed: false },
      { id: 6, title: "Power BI", duration: "35:00", free: false, completed: false },
    ],
    questions: [
      { id: 1, question: "ما هي أداة تحليل البيانات الأشهر؟", options: ["Photoshop", "Excel", "Word", "Paint"], correct: 1 },
      { id: 2, question: "ما هو الـ DataFrame؟", options: ["جدول بيانات", "رسم", "ملف", "برنامج"], correct: 0 },
      { id: 3, question: "ما هي مكتبة التحليل في Python؟", options: ["Django", "Pandas", "Flask", "os"], correct: 1 },
      { id: 4, question: "ما هو الـ Dashboard؟", options: ["لوحة عرض بيانات", "قاعدة بيانات", "برنامج", "ملف"], correct: 0 },
      { id: 5, question: "ما هو الـ KPI؟", options: ["مؤشر أداء رئيسي", "برنامج", "لغة", "ملف"], correct: 0 },
    ],
    certificateTitle: "Data Analysis - تحليل البيانات",
    emoji: "📊",
    color: "from-emerald-500 to-green-400",
    gradientFrom: "from-emerald-600/20",
    gradientTo: "to-green-600/20",
  },
  13: {
    id: 13,
    category: "Testing",
    title: "Software Testing - اختبار البرمجيات",
    description: "تعلم اختبار البرمجيات من الصفر. الكورس يغطي Manual Testing, Automation, Selenium, Test Cases, QA وأكتر.",
    rating: 4.6,
    students: 480,
    duration: "22 ساعة",
    lessonsCount: 26,
    price: 39,
    instructor: "Hoda Mahmoud",
    topics: ["Testing Basics", "Test Cases", "Manual Testing", "Selenium", "API Testing", "QA Process"],
    lessons: [
      { id: 1, title: "مقدمة في Testing", duration: "12:00", free: true, completed: false },
      { id: 2, title: "أنواع الاختبارات", duration: "18:30", free: true, completed: false },
      { id: 3, title: "كتابة Test Cases", duration: "25:15", free: false, completed: false },
      { id: 4, title: "Selenium Basics", duration: "30:00", free: false, completed: false },
      { id: 5, title: "API Testing", duration: "28:10", free: false, completed: false },
      { id: 6, title: "QA Process", duration: "30:00", free: false, completed: false },
    ],
    questions: [
      { id: 1, question: "ما هو الـ Bug؟", options: ["ميزة", "عيب في البرنامج", "برنامج", "لغة"], correct: 1 },
      { id: 2, question: "ما هي أداة الـ Automation الأشهر؟", options: ["Excel", "Selenium", "Word", "Paint"], correct: 1 },
      { id: 3, question: "ما هو الـ Test Case؟", options: ["حالة اختبار موثقة", "خطأ", "كود", "ملف"], correct: 0 },
      { id: 4, question: "ما هو الـ Regression Testing؟", options: ["اختبار جديد", "إعادة اختبار بعد تعديل", "حذف", "تصميم"], correct: 1 },
      { id: 5, question: "ما هو الـ QA؟", options: ["ضمان الجودة", "برنامج", "لغة", "جهاز"], correct: 0 },
    ],
    certificateTitle: "Software Testing - اختبار البرمجيات",
    emoji: "🧪",
    color: "from-amber-500 to-yellow-400",
    gradientFrom: "from-amber-600/20",
    gradientTo: "to-yellow-600/20",
  },
  14: {
    id: 14,
    category: "DevOps",
    title: "DevOps - تطوير ونشر العمليات",
    description: "تعلم DevOps من الصفر. الكورس يغطي Git, Docker, CI/CD, Kubernetes, Cloud Deployment, Monitoring وأكتر.",
    rating: 4.7,
    students: 550,
    duration: "32 ساعة",
    lessonsCount: 38,
    price: 59,
    instructor: "Karim Samir",
    topics: ["Git & Version Control", "Docker", "CI/CD Pipelines", "Kubernetes", "Cloud (AWS)", "Monitoring"],
    lessons: [
      { id: 1, title: "مقدمة في DevOps", duration: "12:00", free: true, completed: false },
      { id: 2, title: "Git المتقدم", duration: "20:30", free: true, completed: false },
      { id: 3, title: "Docker & Containers", duration: "28:15", free: false, completed: false },
      { id: 4, title: "CI/CD Pipelines", duration: "32:00", free: false, completed: false },
      { id: 5, title: "Kubernetes", duration: "38:10", free: false, completed: false },
      { id: 6, title: "Cloud Deployment", duration: "35:00", free: false, completed: false },
    ],
    questions: [
      { id: 1, question: "ما هو Docker؟", options: ["برنامج حاويات", "لغة", "متصفح", "قاعدة بيانات"], correct: 0 },
      { id: 2, question: "ما هو CI/CD؟", options: ["تكامل ونشر مستمر", "برنامج", "لغة", "جهاز"], correct: 0 },
      { id: 3, question: "ما هو Kubernetes؟", options: ["إدارة الحاويات", "برنامج تصميم", "لغة", "شبكة"], correct: 0 },
      { id: 4, question: "ما هو Git؟", options: ["نظام إدارة إصدارات", "محرر", "متصفح", "سيرفر"], correct: 0 },
      { id: 5, question: "ما هي أشهر منصة سحابية؟", options: ["AWS", "Photoshop", "Excel", "Zoom"], correct: 0 },
    ],
    certificateTitle: "DevOps - تطوير ونشر العمليات",
    emoji: "⚙️",
    color: "from-sky-500 to-blue-400",
    gradientFrom: "from-sky-600/20",
    gradientTo: "to-blue-600/20",
  },
  15: {
    id: 15,
    category: "Generative AI",
    title: "Generative AI - الذكاء الاصطناعي التوليدي",
    description: "تعلم الذكاء الاصطناعي التوليدي: ChatGPT APIs, Prompt Engineering, بناء تطبيقات AI, RAG, Fine-tuning وأكتر.",
    rating: 4.9,
    students: 1100,
    duration: "25 ساعة",
    lessonsCount: 30,
    price: 69,
    instructor: "Dr. Layla Mostafa",
    topics: ["LLM Basics", "Prompt Engineering", "OpenAI API", "RAG", "Fine-tuning", "AI Apps"],
    lessons: [
      { id: 1, title: "مقدمة في Generative AI", duration: "12:00", free: true, completed: false },
      { id: 2, title: "كيف تعمل نماذج اللغة", duration: "20:30", free: true, completed: false },
      { id: 3, title: "Prompt Engineering", duration: "25:15", free: false, completed: false },
      { id: 4, title: "OpenAI API", duration: "30:00", free: false, completed: false },
      { id: 5, title: "RAG & Embeddings", duration: "35:10", free: false, completed: false },
      { id: 6, title: "بناء تطبيق AI كامل", duration: "45:00", free: false, completed: false },
    ],
    questions: [
      { id: 1, question: "ما هو الـ Prompt Engineering؟", options: ["برمجة", "صياغة أوامر فعالة للنماذج", "تصميم", "اختبار"], correct: 1 },
      { id: 2, question: "ما هو الـ RAG؟", options: ["دمج معرفة خارجية بالنموذج", "لغة", "برنامج", "قاعدة بيانات"], correct: 0 },
      { id: 3, question: "ما هو الـ Fine-tuning؟", options: ["تدريب النموذج على بيانات مخصصة", "حذف", "نسخ", "طباعة"], correct: 0 },
      { id: 4, question: "ما هو الـ Token في LLM؟", options: ["عملة", "جزء من النص", "برنامج", "ملف"], correct: 1 },
      { id: 5, question: "ما هو ChatGPT؟", options: ["متصفح", "نموذج لغوي توليدي", "لغة برمجة", "جهاز"], correct: 1 },
    ],
    certificateTitle: "Generative AI - الذكاء الاصطناعي التوليدي",
    emoji: "✨",
    color: "from-fuchsia-500 to-pink-400",
    gradientFrom: "from-fuchsia-600/20",
    gradientTo: "to-pink-600/20",
  },
};

export function getCourseById(id: number): CourseData | undefined {
  return coursesData[id];
}

export function getAllCourses(): CourseData[] {
  return Object.values(coursesData);
}
